baseURL = 'http://sigma.velocidex.com/'
languageCode = 'en-us'
title = 'Velociraptor Curated Sigma'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[markup.goldmark.renderer]
unsafe= true

[params]
BookTheme = 'light'
BookSearch = false